service: sls-example

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudtrail:StartLogging"
      Resource:
        - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:cloudtrail'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'trail/default'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  golang:
    handler: bin/handler
    events:
      - schedule: rate(1 day)
